{{- if .Values.service.dns.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "acme-dns.fullname" . }}-dns
  labels:
    {{- include "acme-dns.labels" . | nindent 4 }}
  {{- with .Values.service.dns.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.dns.type }}
  {{- if and (eq .Values.service.dns.type "LoadBalancer") .Values.service.dns.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.dns.externalTrafficPolicy }}
  {{- end }}
  {{- with .Values.service.dns.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  selector:
    {{- include "acme-dns.selectorLabels" . | nindent 4 }}
  ports:
    - name: dns-tcp
      port: {{ .Values.service.dns.port }}
      targetPort: dns-tcp
      protocol: TCP
    - name: dns-udp
      port: {{ .Values.service.dns.port }}
      targetPort: dns-udp
      protocol: UDP
{{- end }}
{{- if and .Values.service.dns.enabled .Values.service.api.enabled }}
---
{{- end }}
{{- if .Values.service.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "acme-dns.fullname" . }}-api
  labels:
    {{- include "acme-dns.labels" . | nindent 4 }}
  {{- with .Values.service.api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.api.type }}
  selector:
    {{- include "acme-dns.selectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.service.api.port }}
      targetPort: api
      protocol: TCP
{{- end }}
